version: '3.1'

services:
  nginx:
    image: phixyz/fediunifrontend:dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./dist/:/usr/share/nginx/html/
    networks:
      - fediuni
    depends_on:
      - activitypub
  activitypub:
    image: phixyz/fediuni
    container_name: fediuni-xyz
    secrets:
      - config
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    networks:
      - fediuni
  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - fediuni
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  fediuni:

volumes:
  redis:
    external: true

secrets:
  config:
    file: ~/code/src/github.com/FediUni/FediUni/config.yaml
