version: '3.1'

services:
  nginx:
    image: phixyz/fediunifrontend:dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./dist:/usr/share/nginx/html
    networks:
      - fediuni
    depends_on:
      - activitypub
  activitypub:
    image: phixyz/fediuni
    container_name: fediuni-xyz
    ports:
    - "8080:8080"
    secrets:
      - config
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
      - mongo
    networks:
      - fediuni
  redis:
    image: redis
    volumes:
      - redis:/data
    networks:
      - fediuni
    command: redis-server --requirepass ${REDIS_PASSWORD}
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - fediuni


networks:
  fediuni:

volumes:
  redis:
    external: true

secrets:
  config:
    file: config.yaml
